### ISSUE TITLE
BundleMon GitHub Action keeps listing assets as "added"

### ISSUE THREAD

**Issue by aversini** [LironEr/bundlemon-action#20]
Hello @LironEr , I have implemented BundleMon and its corresponding GitHub Action in one of my projects. It's working well (thank you!) and triggered for every PR, however, I cannot figure out a way to make it remember the project. Each time a PR runs, it displays the following:

<img width="535" alt="Screenshot 2023-09-26 at 12 50 08 PM" src="https://github.com/LironEr/bundlemon-action/assets/38716/e7b00989-8b3e-437a-9c5c-723258f85311">

See the "Files added" label. Even though that it's not the first PR that ran with BundleMon on that repo. The repo is there: https://github.com/aversini/mylogin-ui and the corresponding BundleMon configuration file is here: https://github.com/aversini/mylogin-ui/blob/main/bundlemon.config.cjs

Thanks!

**Comment by LironEr** [comment]
Hey, thanks for reaching out (:

So it looks like you are missing running bundlemon on each commit on your main branch.

for [example](https://github.com/LironEr/bundlemon-github-actions/blob/main/.github/workflows/build.yml):
```
on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened]
```

You need to run bundlemon on each commit on your main branch because when you create a PR and you have a target branch, bundlemon checks the file sizes on that branch and compares them to your PR.

Only after you merge something (push to main) bundlemon can save the new file sizes to that branch, and it becomes the new baseline.

**Comment by aversini** [comment]
That did it, thanks for the tip @LironEr 👍
